### ISSUE TITLE
(Bug) After a second launch of the tool is not collecting events on Core

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/poa-ballot-stats#10]
```
master ~/r/poa-ballot-stats> cargo run -- -c contracts/core.json https://core.poa.network -v
    Finished dev [unoptimized + debuginfo] target(s) in 0.28 secs
     Running `target/debug/poa-ballot-stats -c contracts/core.json 'https://core.poa.network' -v`
Collecting events…
thread 'main' panicked at 'count votes: Error(NoEventsFound, State { next_error: None, backtrace: None })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
exit 101
```

**Comment by afck** [comment]
For me, results with https://core.poa.network are completely unpredictable: https://github.com/poanetwork/poa-ballot-stats/issues/4

The query seems to sometimes return incomplete and sometimes empty results.

**Comment by igorbarinov** [comment]
@phahulin let's test in on each individual node
@afck can we make an option to do not check SSL certs? under Load Balancers nodes are with self signed certs

**Comment by afck** [comment]
It looks like the web3 crate doesn't support configuring that. But if the problem was related to the certificate, wouldn't the connection fail entirely? It seems like it succeeds making the connection and making the query but then gets wrong results (without an error).

Edit: I'm happy to try and get SSL options added into the web3 crate. It would make sense to make the `Http` transport more configurable.

**Comment by igorbarinov** [comment]
I was thinking to test individual nodes in the load balancer to figure out what's going on.
They have self-signed certificates and the tool returns an error
```
master ~/r/poa-ballot-stats> cargo run -- -c contracts/core.json https://poa.jp -v
    Finished dev [unoptimized + debuginfo] target(s) in 0.22 secs
     Running `target/debug/poa-ballot-stats -c contracts/core.json 'https://poa.jp' -v`
thread 'main' panicked at 'get latest block: Error(Transport("Io(Custom { kind: Other, error: Error { code: -67843, message: \"The certificate was not trusted.\" } })"), State { next_error: None, backtrace: None })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
exit 101
```
