### ISSUE TITLE
Accurately compute the set of validators at any given block.

### ISSUE THREAD

**Issue by afck** [poanetwork/poa-ballot-stats#16]
The current implementation estimates the set of validators based on `InitializeChange` events, which is [sometimes wrong](https://github.com/poanetwork/poa-ballot-stats/issues/14) because those don't necessarily get finalized and if they do, it's only in some later block. Unfortunately we [don't have `ChangeFinalized`](https://github.com/paritytech/parity/issues/7141) in the logs.

If the node runs with `--pruning=archive`, it would be possible to use the contract states at any given point, and call the contract methods to retrieve the validators. However, that would mean that the tool would stop working with https://sokol.poa.network and https://core.poa.network (https://core-trace.poa.network and https://sokol-trace.poa.network could be used instead, though).

**Comment by afck** [comment]
@igorbarinov: Is it okay to sacrifice compatibility with https://sokol.poa.network and https://core.poa.network for accurate membership data?

**Comment by igorbarinov** [comment]
@afck yes, let's specify that the requirement is to query a trace node 
@phahulin what is the launch string for the trace node? to include it into the document

**Comment by phahulin** [comment]
In this case, as I understand, traces are not required actually, just `--pruning=archive` cli option should suffice
