### ISSUE TITLE
(Question) What is the format of JSON with the contract addresses

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/poa-ballot-stats#2]
Hi @afck ,
when I run `cargo run -- -h`
there is an option to specify a JSON file with the contract addresses. 
```
OPTIONS:
    -c, --contracts <contracts>    JSON file with the contract addresses
```
- what is the format of the JSON file
- could we have JSON files with the tool for the Sokol/Core networks?

**Comment by afck** [comment]
It's the `contracts.json` from the `core` or `sokol` branch of: https://github.com/poanetwork/poa-chain-spec/

I don't think we should duplicate those files here, but I'll add some documentation.

**Comment by afck** [comment]
I added it to the Readme: https://github.com/poanetwork/poa-ballot-stats/commit/c9a7c42b82e2ffa3941886666190e1abf7a6b595
