### ISSUE TITLE
(Update) Add support for updated consensus contracts

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-ballot-stats#20]
**Problem:** We have [updated consensus smart contracts](https://github.com/poanetwork/poa-network-consensus-contracts/tree/ec307069302fdf6647e8b1bdc13093960913b266/contracts) that are going to be deployed in `Sokol` network in the next few days.

**Solution:** Please check the code of the tool and add support for new contracts if needed. The [new contracts](https://github.com/poanetwork/poa-network-consensus-contracts/tree/ec307069302fdf6647e8b1bdc13093960913b266/contracts) are slightly different from [old ones](https://github.com/poanetwork/poa-network-consensus-contracts/tree/aa45e19ca50f7cae308c1281d950245b0c65182a/contracts), so some changes in the tool may need to be done.

**Comment by varasev** [comment]
Hi @afck,

Please take a look at this issue.

**Comment by varasev** [comment]
The new smart contracts were deployed in `Sokol` on `September 13` and in `Core` on `October 8`. They are already in use in `Sokol` ([Sokol HF 3](https://github.com/poanetwork/wiki/wiki/HFs-Sokol-2018-09-19)) and will be used in `Core` from `October 22` ([Core HF 2](https://github.com/poanetwork/wiki/wiki/HFs-Core-2018-10-22)), so I think it's time to start implementation of this issue.

**Comment by afck** [comment]
Thank you! I already have it mostly ready. I'll make a PR early next week.
